V5 docs using sql provider sql server ssdt
SAFE-Stack/docs pull request #341
Opened 2023-12-22 19:07 UTC by OutOfScopeia

Updates to the 'use SQL provider' recipe.
[x] Updates to code snippets (tasks given where asyncs were expected)
[x] Update instructions to add NuGet packages from FAKEless style to FAKEful-style
[x ]updating screenshots for the recipe
[ ] Make project build with the NuGet packages it adds
[ ] Make sure SQL connection string in a snippet (**"Data Source=.\SQLEXPRESS;Initial Catalog=SafeTodo;Integrated Security=SSPI;**) is tested for both scenarios (Local SQL Express and Docker SQL) and put in note of any differences if need be.

2023-12-27 17:46 UTC, Larocceau commented
There seems to be something wrong in the dependencies of one of the packages, which then fails at build because "Microsoft.Data.SqlClient" Version="5.0.0" is missing.


hacky workround is adding it directly as a dependency of server.:

```
  <ItemGroup>
      <PackageReference Include="Microsoft.Data.SqlClient" Version="5.0.0" />
  </ItemGroup>
```

2024-01-02 17:08 UTC, Larocceau commented on docs/recipes/storage/use-sqlprovider-ssdt.md
> +    let db = Database.createContext @"Data =.\SQLEXPRESS,1433;Database=SafeTodo;User ID=sa;Password=yourStrong(!)Password;Encrypt=false"
Could not get this to work with the original Connection string  "Data Source=.\SQLEXPRESS;Initial Catalog=SafeTodo;Integrated Security=SSPI;". I suppose that one could be used for both a prod and local environment? I feel like adding instructions on how to have separate connection strings for prod and local might be useful anyway. Should we get the old connection string to work, or should we add instructions on how to add separate connection strings?

2024-01-03 15:50 UTC, theprash requested changes

2024-01-03 15:50 UTC, theprash commented on docs/recipes/storage/use-sqlprovider-ssdt.md
> +## set up your database Server using Docker
```suggestion
## Set up your database Server using Docker
```

2024-01-03 16:24 UTC, theprash approved these changes

2024-01-03 16:24 UTC, merged